### ISSUE TITLE
use Dart interoperability to call Wear API

### ISSUE THREAD

**Issue by billyandco** [gardyna/wearable_communicator#8]
Hi ! very interesting library
Are you planing to use Dart interoperability to complete your todos ?
https://www.youtube.com/watch?v=ZWp2FJ2TuJs

i think it will helps a lot by avoiding PlatformChannel

**Comment by gardyna** [comment]
I have not had the time or incentive to maintain this project. I do not expect that to change in near future so you can assume that this plugin is abandoned.

**Comment by billyandco** [comment]
Oh i see ! thank you for answering ! 👌
